name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Устанавливаем Node.js с помощью actions/setup-node
      - name: Set up Node.js (v20.x)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Проверка и деплой клиента
      - name: Check if Client was updated
        id: client
        run: |
          git fetch origin
          git diff --exit-code --quiet origin/main -- client
        continue-on-error: true  # Не прерываем выполнение, если изменений нет

      - name: Install Dependencies and Build Client
        if: steps.client.outcome == 'success'  # Если были изменения в client
        run: |
          cd client
          yarn install
          yarn build

      - name: Deploy Client to Server
        if: steps.client.outcome == 'success'
        run: |
          scp -i deploy_key.pem -r client/dist/* user@your-server:/var/www/wttw/dist
          ssh -i deploy_key.pem user@your-server "sudo systemctl restart nginx"

      # Проверка и деплой API
      - name: Check if API was updated
        id: api
        run: |
          git fetch origin
          git diff --exit-code --quiet origin/main -- api
        continue-on-error: true  # Не прерываем выполнение, если изменений нет

      - name: Install Dependencies and Build API
        if: steps.api.outcome == 'success'  # Если были изменения в api
        run: |
          cd api
          yarn install
          yarn build

      - name: Deploy API to Server
        if: steps.api.outcome == 'success'
        run: |
          scp -i deploy_key.pem -r api/* user@your-server:/var/www/wttw/api
          ssh -i deploy_key.pem user@your-server "sudo systemctl restart your-api-service"
