name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem

      - name: Set up Node.js (v20.x)
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies (Client)
        if: contains(github.event.head_commit.message, 'client')
        run: |
          cd client
          yarn install
          yarn build

      - name: Deploy Client to Server
        if: contains(github.event.head_commit.message, 'client')
        run: |
          scp -i deploy_key.pem -r client/dist/* user@your-server:/var/www/wttw/dist
          ssh -i deploy_key.pem user@your-server "sudo systemctl restart nginx"

      - name: Install Dependencies (API)
        if: contains(github.event.head_commit.message, 'api')
        run: |
          cd api
          yarn install
          yarn build

      - name: Deploy API to Server
        if: contains(github.event.head_commit.message, 'api')
        run: |
          scp -i deploy_key.pem -r api/* user@your-server:/var/www/wttw/api
          ssh -i deploy_key.pem user@your-server "sudo systemctl restart your-api-service"
