name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install NVM and Node.js (v20.x)
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
          source ~/.bashrc
          nvm install 20
          nvm use 20
          node -v # Проверяем версию Node.js

      - name: Install Dependencies (Client)
        if: contains(github.event.head_commit.message, 'client')
        run: |
          cd client
          yarn install
          yarn build

      - name: Deploy Client to Server
        if: contains(github.event.head_commit.message, 'client')
        run: |
          scp -i deploy_key.pem -r client/dist/* user@your-server:/var/www/wttw
          ssh -i deploy_key.pem user@your-server "sudo systemctl restart nginx"

      - name: Install Dependencies (API)
        if: contains(github.event.head_commit.message, 'api')
        run: |
          cd api
          yarn install
          yarn build

      - name: Deploy API to Server
        if: contains(github.event.head_commit.message, 'api')
        run: |
          scp -i deploy_key.pem -r api/* user@your-server:/path/to/api
          ssh -i deploy_key.pem user@your-server "sudo systemctl restart your-api-service"
